### ISSUE TITLE
Error "Cannot access a closed Stream." with internet explorer, pdf and RangeFileStreamResult

### ISSUE THREAD

**Issue by fa18swiss** [tpeczek/Lib.Web.Mvc#99] opened 2016-03-16 13:38 UTC
On first load of a PDF with Internet Explorer 11 (internal pdf reader). i have the following crash : 

```
Cannot access a closed Stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at Lib.Web.Mvc.RangeFileStreamResult.WriteEntityRange(HttpResponseBase response, Int64 rangeStartIndex, Int64 rangeEndIndex)
   at Lib.Web.Mvc.RangeFileResult.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

Usage : 

```
return new RangeFileStreamResult(file.Content, file.ContentType, file.Name, file.LastModification);
```

where file is a custom obect, and file.Content a MemoryStream (copy of a FileStream)

**Comment by tpeczek** [comment] 2016-03-17 10:56
It seems like the MemoryStream you are passing is already closed (this is often being done via libraries which are writtting to streams like for example SharpPDF).

In order to guide you further I need to know more about how that file instance is being created and used.

**Comment by fa18swiss** [comment] 2016-03-19 15:35
The stream is not closed otherwise it will crash in every case.

I can't publish more code, I will try to create a stample application who repoduce the problem

**Comment by tpeczek** [comment] 2017-02-24 10:19
Closing due to not enough information to reproduce or investigate further.

**Closed by tpeczek** 2017-02-24 10:19 UTC
Labels: Issue, RangeFileResult
